config/routes.rb
Rails.application.routes.draw do

#add in session and index routes
#guides.rubyonrails.orb/routing.html
  get '/' => 'sessions#index'
  get '/login' => 'sessions#new' #this starts a new session when a user logs in 
  post '/login' => 'sessions#create' #post the login information to create the session
  delete '/logout' => 'sessions#destroy' #destroy the session when a user logs out

  get '/signup' => 'users#new'  #you do not need a post sign up here because the user will be created 

  get '/auth/google_oauth2/callback' => 'sessions#omniauth'
  #get '/auth/:provider/callback' => 'sessions#create' #only use this if there are multiple providers

  get '/pizzas/most_popular_pizzas' => 'pizzas#most_popular_pizza'
 
  #resources writes out the 7 restful routes, but only write the routes for methods you are using.
  resources :ratings
  resources :pizzas do 
  resources :ratings, only: [:new, :index, :show] #nested routes
  end 
  resources :restaurants
  resources :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/pizza.rb
class Pizza < ApplicationRecord
  belongs_to :user #Whoever created the pizza
  belongs_to :restaurant
  has_many :ratings
  has_many :users, through: :ratings #these are the users who have rated the pizza
  accepts_nested_attributes_for :restaurant #necessary if using a nested form 
  validates :specialtyname, presence: true
  validates :toppings, presence: true

  #scopes 
  #to find the highest rated pizza - join the two tables (pizza and rating) Pizza.joins(:ratings).group(:id).order('avg(rate) desc'))
  scope :highest_avg_rating_order, -> {Pizza.joins(:ratings).group(:id).order('avg(rate) desc')}
  #scope :most_popular_pizza, -> {Pizza.joins(:ratings).group(:id).order('avg(rate) desc').first} --> Find this within controller


  def not_a_duplicate #custom validation
    #query the db - if a pizza is already created with the same specialtyname and restaurant, thow an error
    #check this in rails c - Pizza.find_by(specialtryname: 'Mellow Mushroom', restaurant_id: 1)
    if Pizza.find_by(specialtyname: specialtyname, restaurant_id: restaurant_id)
        errors.add(:specialtyname, "This pizza is already created. Please add a new pizza.")
    end 
  end 

  def specialtyname_and_restaurant #this method is used to list multiple things within the collection select
    "#{specialtyname} - #{restaurant.name}"
  end 
  
  #--- add in the restaurant attributes - create a restaurant if the name is not empty - This is the logic that lets you save the dropdown 
  #https://medium.com/@ryanwerner_57863/how-to-build-a-nested-form-in-rails-using-fields-for-c185210f6869
  def restaurant_attributes=(attributes)
    self.restaurant = Restaurant.find_or_create_by(attributes) if 
      !attributes['name'].empty?
    self.restaurant
  end

end

app/controllers/pizzas_controller.rb
class PizzasController < ApplicationController
    before_action :not_logged_in_helper, on: [:create, :show, :index] #before each method, verify that a user is logged in
    def new 
        @pizza = Pizza.new 
        @pizza.build_restaurant #tell pizza to build the restaurant because its within a nested form
    end 

    def create 
        @pizza = Pizza.new(pizza_params)
        @pizza.user_id = session[:user_id]
            if @pizza.save #validations occur on the save
                redirect_to pizza_path(@pizza), :notice => "Your Pizza Was Saved"
            else 
                @pizza.build_restaurant
                render :new
            end 
    end 

    def index #this is an index action
        #@pizzas = Pizza.all.order_by_rating
        @pizzas = Pizza.all
        @pizza = Pizza.find_by_id(params[:id])
        @most_popular_pizza = Pizza.highest_avg_rating_order.first    #show most popular pizza here
    end 

    def show 
        @pizza = Pizza.find_by_id(params[:id])
    end 

    def most_popular_pizza
        @most_popular_pizza =  Pizza.highest_avg_rating_order.first
        @second_popular_pizza = Pizza.highest_avg_rating_order.second
        @third_popular_pizza = Pizza.highest_avg_rating_order.third
    end 


    private 

        def pizza_params #strong params - provides an interface for protecting attributes from end-user assignment
            #parameters can be marked as required and flow through a predefined raise/rescue flow to end up as a 400 Bad Request with no effort
            #In order to use accepts_nested_attributes_for with Strong Parameters, you will need to specify which nested attributes should be permitted
            params.require(:pizza).permit(:specialtyname, :toppings, :restaurant_id, restaurant_attributes: [:name,:city,:state,:website])
        end 

        def pizza_find_by
            @pizza = Pizza.find_by_id(params[:id])
        end 

       
end

app/helpers/pizzas_helper.rb
module PizzasHelper
end

app/views/pizzas/_form.erb
 <%= render :partial => 'layouts/header' %>
<h1>Make a new pizza</h1>

<%= form_for(@pizza) do |f| %>
    <%= f.label :specialtyname, "Specialty Name:" %>
    <%= f.text_field :specialtyname %>
   <br>
    <br>
    <%= f.label :toppings, "Toppings:" %>
    <%= f.text_field :toppings %>
   <br>
   <br>
    <p>Select a Restaurant:<p>
    <!--Assign this the resturant id-->
    <!--Collection_select(object, method, collection, value_method(id), text_method(what is displayed), options-->
        <%= f.collection_select :restaurant_id, Restaurant.all, :id, :name, include_blank: 'Select Restaurant' %>

    <p>Or create a<b> new Restaurant</b><p>
    <!--We need this to write attributes of another object AKA this is my nested form-->
    <!--When doing a nested form, use the fields_for-->
    <div>
        <%=f.fields_for :restaurant do |r|%>
            <%= r.label :name, "Name:"%>
            <%= r.text_field :name %>
            <br>
            <%= r.label :city, "City:"%>
            <%= r.text_field :city %> 
            <br>
            <%= r.label :state, "State:"%>
            <%= r.select :state, options_for_select(us_states) %>
            <br>
            <%= r.label :website, "Website"%>
            <%= r.text_field :website %>
        <%end %>
    </div>

    <br>

    <%= f.submit "Add a New Pizza"%>

<% end %>

app/views/pizzas/edit.html.erb
<h1>Update a Pizza</h1>

<%= form_for(@object) do |f| %>
    <%= f.label :specialtyname, "Specialty Name:" %>
    <%= f.text_field :specialtyname %>
   <br>
    <br>
    <%= f.label :toppings, "Toppings:" %>
    <%= f.text_field :toppings %>
   <br>
<%= f.submit "Add a New Pizza"%>

app/views/pizzas/index.html.erb
 <%= render :partial => 'layouts/header' %>
<h1>Pizzas</h1>

<h2> <b> <%= link_to "Most Popular Pizza in the USA:", pizzas_most_popular_pizzas_path %> <%= @most_popular_pizza.specialtyname_and_restaurant%> </b></h2>
<br>
<h2>See below the other tasty Pizzas!</h2>
<ol>
    <% @pizzas.each do |p| %>
        <li><b>Restaurant:</b> <%= p.restaurant.name %> | <b>Specialty Name:</b> <%= p.specialtyname %> 
        <%= link_to "Rate this Pizza", new_pizza_rating_path(p.id)%> <!--pass in the pizza_id (p.id) in this nested route--> or view <%= link_to "All Ratings for this Pizza", pizza_ratings_path(p)%></li>
    <%end %>
</ol>

app/views/pizzas/most_popular_pizza.html.erb
<%= render :partial => 'layouts/header' %>
<br>
<h2>Top Pizza: <%=@most_popular_pizza.specialtyname_and_restaurant %> </h2>
<h2>Second Pizza: <%=@second_popular_pizza.specialtyname_and_restaurant %></h2>
<h2>Third Pizza: <%=@third_popular_pizza.specialtyname_and_restaurant %></h2>

app/views/pizzas/new.html.erb
 <%= render :partial => 'layouts/header' %>
<h1>Make a new pizza</h1>

<%= form_for(@pizza) do |f| %>
    <%= f.label :specialtyname, "Specialty Name:" %>
    <%= f.text_field :specialtyname %>
   <br>
    <br>
    <%= f.label :toppings, "Toppings:" %>
    <%= f.text_field :toppings %>
   <br>
   <br>
    <p>Select a Restaurant:<p>
    <!--Assign this the resturant id-->
    <!--Collection_select(object, method, collection, value_method(id), text_method(what is displayed), options-->
        <%= f.collection_select :restaurant_id, Restaurant.all, :id, :name, include_blank: 'Select Restaurant' %>
    <!--collection_select(:pizza, :restaurant_id, Restaurant.all, :id, :name, include_blank:-->
    <!--Id of restaurant, array of all restaurants, -->

    <p>Or create a<b> new Restaurant</b><p>
    <!--We need this to write attributes of another object AKA this is my nested form-->
   
    <div>
        <%=f.fields_for :restaurant do |r|%>  <!--When doing a nested form, use the fields_for-->
            <%= r.label :name, "Name:"%>
            <%= r.text_field :name %>
            <br>
            <%= r.label :city, "City:"%>
            <%= r.text_field :city %> 
            <br>
            <%= r.label :state, "State:"%>
            <%= r.select :state, options_for_select(us_states) %> <!--Use a select tag with options built in the Resturant helper-->
            <br>
            <%= r.label :website, "Website"%>
            <%= r.text_field :website %>
        <%end %>
    </div>
    <br>
    <%= f.submit "Add a New Pizza"%>

<% end %>
<%= render partial: 'layouts/errors', locals: {object: @pizza} %>

app/views/pizzas/show.html.erb
<%= render :partial => 'layouts/header' %>
<style>
table, th, td {
  border: 3px solid black;
  border-spacing: 10px;
}
</style>
<table class="center" cellpadding="10" >
  <tr>
    <th>Restaurant</th>
    <th>State</th>
    <th>Specialty Name</th>
    <th>Toppings</th>
  </tr>
  <tr>
   <td><%=@pizza.restaurant.name%></td>
   <td><%=@pizza.restaurant.state%></td>
    <td><%=@pizza.specialtyname%></td>
    <td><%=@pizza.toppings%></td>  
    
  </tr>
</table>
<br>

<%= link_to "View Ratings for this Pizza", pizza_ratings_path(@pizza) %>

</body>
</html>