config/routes.rb
Rails.application.routes.draw do

#add in session and index routes
#guides.rubyonrails.orb/routing.html
  get '/' => 'sessions#index'
  get '/login' => 'sessions#new' #this starts a new session when a user logs in 
  post '/login' => 'sessions#create' #post the login information to create the session
  delete '/logout' => 'sessions#destroy' #destroy the session when a user logs out

  get '/signup' => 'users#new'  #you do not need a post sign up here because the user will be created 

  get '/auth/google_oauth2/callback' => 'sessions#omniauth'
  #get '/auth/:provider/callback' => 'sessions#create' #only use this if there are multiple providers

  get '/pizzas/most_popular_pizzas' => 'pizzas#most_popular_pizza'
 
  #resources writes out the 7 restful routes, but only write the routes for methods you are using.
  resources :ratings
  resources :pizzas do 
  resources :ratings, only: [:new, :index, :show] #nested routes
  end 
  resources :restaurants
  resources :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
    has_many :ratings
    has_many :rated_pizzas, through: :ratings, source: :pizza
    has_many :pizzas #pizzas that the user creates within the application
    has_secure_password #has validations built in for password - must enable bcrypt gem
    #validates :password, length: { in: 6..20 } #password must be at least 6 characters
    validates :username, uniqueness: true, presence: true 


    #will be called on user class
    def self.find_or_create_by_google(auth)
        User.find_or_create_by(username: auth[:info][:email]) do |user|
            user.password = SecureRandom.hex #set a random password when using omniauth and SecureRandom.hex
        end 
    end 

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :not_logged_in_helper, on: [:create, :show, :index] #before each method, verify that a user is logged in

    def new 
        @user = User.new
    end 

    def create 
        @user = User.new(user_params)
        if @user.save 
            session[:user_id] = @user.id
            redirect_to user_path(@user)
        else 
            render :new 
        end
    end 

    def show
        @user = User.find_by_id(params[:id])
    end 

    def index
        
    end     

    # def current_user #this method needs to return user that is found by session user id
    #     #||= will only call db once if you are using current user more than once in a method 
    #     #find by id so that if the id is null it wont error out
    #     @current_user ||= User.find_by_id(session[:user_id])
    # end 

    private 

    #this is where you define user_params - user_params is not an action
    def user_params 
        params.require(:user).permit(:username, :password)
    end 

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/index.html.erb
<h1>Test</h1>

app/views/users/new.html.erb
<h1>Sign up</h1>


<!--You want a formfor for signup -->
<%= form_for(@user) do |f| %>
    <%= f.label :username%>
    <%= f.text_field :username%>

    <%= f.label :password%>
    <%= f.password_field :password%>

    <%= f.submit "Sign Up"%>

<% end %>
<%= render partial: 'layouts/errors', locals: {object: @user} %>

app/views/users/show.html.erb
 <%= render :partial => 'layouts/header' %>

<div class="Welcome">
<h1>Welcome, <%=@user.username%></h1>
</div>
<br>
<br>
<h2>Pizza's You Have Created</h2>
<% @user.pizzas.each do |p|%>
 <%= link_to p.specialtyname_and_restaurant, pizza_path(p) %><br>
<% end %>

<br>
<h2>Pizza's You have Reviewed</h2>
<% @user.rated_pizzas.each do |p|%>
 <%= link_to p.specialtyname_and_restaurant, pizza_path(p)%><br>
<% end %>