config/routes.rb
Rails.application.routes.draw do

#add in session and index routes
#guides.rubyonrails.orb/routing.html
  get '/' => 'sessions#index'
  get '/login' => 'sessions#new' #this starts a new session when a user logs in 
  post '/login' => 'sessions#create' #post the login information to create the session
  delete '/logout' => 'sessions#destroy' #destroy the session when a user logs out

  get '/signup' => 'users#new'  #you do not need a post sign up here because the user will be created 

  get '/auth/google_oauth2/callback' => 'sessions#omniauth'
  #get '/auth/:provider/callback' => 'sessions#create' #only use this if there are multiple providers

  get '/pizzas/most_popular_pizzas' => 'pizzas#most_popular_pizza'
 
  #resources writes out the 7 restful routes, but only write the routes for methods you are using.
  resources :ratings
  resources :pizzas do 
  resources :ratings, only: [:new, :index, :show] #nested routes
  end 
  resources :restaurants
  resources :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
    <div id="error_explanation">
    <h2><%= pluralize(object.errors.count, "error") %> prohibited this from being saved: </h2>

    <ul>
    <% object.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
    <% end %>
    </ul>
    </div>
<% end %>

<!--This is standard error boiler plate. Object will refer to the object we are rendering, @user, @review, @pizza, etc.-->

app/views/layouts/_header.html.erb
<!DOCTYPE html>
<html>
<head>
<style>
 .welcome{
        font-size: large;
        color: #1C0703;
        text-align: center
        padding: 25px 50px 75px 100px;
    }
 
</style>
</head>
<body>

<nav class="navbar navbar-expand-lg navbar-light bg-light" >
  <div class="container-fluid">
    <a class="navbar-brand" href="#">On a Mission to find the best pizza in the USA</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
         <li class="nav-link active">
          <li> <%= link_to "Add a Pizza", new_pizza_path %> </li>
        </li>
        <li class="nav-link active">
         <li> <%= link_to "All Ratings", ratings_path %> </li>
        </li>
        <li class="nav-link active">
           <li> <%= link_to "All Restaurants", restaurants_path %> </li>
        </li>
        <li class="nav-link active">
            <li> <%= link_to "All Pizzas", pizzas_path %> </li>
        </li>
        <li class="nav-link active">
          <li><%= link_to "Home", user_path(current_user) %></li>
        </li>
        <li class="nav-link active">
            <li> <%= link_to "Logout", logout_path, method: :delete %> </li> <!--Specify that this is the delete method-->
        </li>
      </ul>
    </div>
  </div>
</nav>
</body>
</html>

app/views/layouts/_loginheader.html.erb
 <!DOCTYPE html>
<html>
<head>
<style>
.index {
 color: #1C0703; font-size: 500%; text-align: center; padding: 250px 70px 250px;
}
.login {
 color: #1C0703; font-size: 100%; text-align: center; padding: 250px 70px 250px;
}
.center{margin-left: auto;
  margin-right: auto;}
</style>
</head>
<body>
</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PizzaRating</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    

    <!--Added in stylesheet from bootstrap.css-->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <style>
    body{
        background-color: #F2D9BB;
        text-align: center;
        font-family: arial, sans-serif;
        font-weight: normal;
    }
  

    p{
        font-size: large;
        text-align: center;
      
    }

    h2{
        font-size: large;
        color: #1C0703;
        text-align: center;
       
    }

    h3{
        font-size: large;
        color: #1C0703;
        text-align: center;
        
    }
    </style>
  </head>

  <!--Create the Nav Bar Here-->
   
      <!--When you link for logout, you need to put a method that specifies this is a delete method-->
      <!--To find these links, type rails routes-->
  <body>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>